eprei/ft_transcendence

Makefile

The postgresql container is the one that used the database volume. 
Even if you stopped all containers, they can be restarted at any time and docker doesn't allow you to delete the volume of an existing container, whether it's awake or asleep.
Solution: before removing the volume, remove the container using it: **our-postgresql**
My first solution was to run docker-compose down before removing the volume, but that removes all the containers and the network, which may not be necessary when you just want to clean the db.
Feel free to propose changes if you have a better idea.

make clean-database now works without erasing everything

---

backend/entrypoint.sh

I generate a symbolic link of the nest-cli into a `PATH` folder
```bash
make cmd-back
nest --help
```
Nestjs/cli should print a help message
* `man 1 ln`

backend: link nestjs/cli

---

frontend/package-lock.json

there is 1 high severity vulnerability printed in the log after execute `make`
I did this:
```
docker exec -it our-frontend sh
/app # npm audit
vite  4.3.0 - 4.3.8
Severity: high
Vite Server Options (server.fs.deny) can be bypassed using double forward-slash (//) - https://github.com/advisories/GHSA-353f-5xf4-qw67
fix available via `npm audit fix`
node_modules/vite
1 high severity vulnerability
To address all issues, run:
npm audit fix
/app # npm audit fix
changed 1 package, and audited 214 packages in 3s
40 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
/app # exit
```

frontend: update vulnerability

---

Makefile

The command ```docker volume prune -f``` did not remove the docker volume **our-volume**, so I propose to use ```docker compose down --volumes``` instead.

Delete docker volume when make kill-your-work

---

backend/src/auth/guards/authenticated.guard.ts
backend/src/auth/guards/oauth.guard.ts
backend/src/auth/session.serializer.ts

- AuthenticatedGuard is a single guard
that will be in charge of protecting
endpoints by verifying that all necessary
authentications have been successfully
performed (42login + 2fa if the user has
it enabled).
- Addition of explanatory comments

Authenticated guard creation

---

backend/src/app.module.ts

During a rebase in which I imported all database changes from r_database (recently merged into stage), I inadvertently removed AuthModule from the imports in app.module.ts, making the auth controllers unavailable.

import AuthModule

---

backend/src/app.service.ts
backend/src/typeorm/user.entity.ts
backend/src/user/dto/create-user.dto.ts

This branch just changes User property login to nickname.
Why?
Because the user must be able to choose another name for himself, so at first, when the user login for the first time it will be its 42 login name and then it will possibly change to whatever he wants (but it must be unique).
Why not first_name as we talk together (with Samuel and Emiliano)?
Because it must be unique, and 42 logins are unique but first_name are not.

user login is now user nickname

---

frontend/src/components/profile/ClickableIcon.tsx
frontend/src/components/profile/Friend.tsx
frontend/src/components/profile/StatisticElement.tsx
frontend/src/components/profile/UserInformation.tsx

because when we build the frontend we
receive this error:
```
src/components/profile/ClickableIcon.tsx(1,1): error TS6133: 'React' is declared but its value is never read.
src/components/profile/Friend.tsx(1,1): error TS6133: 'React' is declared but its value is never read.
src/components/profile/StatisticElement.tsx(1,1): error TS6133: 'React' is declared but its value is never read.
src/components/profile/UserInformation.tsx(1,1): error TS6133: 'React' is declared but its value is never read.
```
```bash
sed -i \
':a;N;$!ba;s/import React from .react.\n//g' \
$(find frontend/src/components/profile -type f)
```
* [how-can-i-replace-each-newline-n-with-a-space-using-sed](https://stackoverflow.com/questions/1251999/how-can-i-replace-each-newline-n-with-a-space-using-sed)

frontend: remove import react

---

frontend/src/components/profile/Statistics.tsx
frontend/src/components/profile/UserInformation.tsx
frontend/src/pages/MainProfile.tsx

This is a small refactoring.
There was a problem sometimes when ```<MainProfile />``` was re-rending, a inifinite loop was created with the store.
Now the store is update with the data from the loader and nothing more.
Statistics.tsx and UserInformation.tsx don't get props anymore but they each fetch the data they need in the store directly.

R profile refactor

---

frontend/src/components/profile/StatisticsLambda.tsx
frontend/src/pages/UserLambda.tsx

The functionality did not work because the
element was based on an old version of the
'statistics' element.
Hotfix: recreate the old element and call it 
StatisticsLambda.
How to test it? In the Stage branch try to 
access localhost:4040/user/user1 and you 
will see that it does not work. 
This pull request allows localhost:
4040/user/user1 to work correctly.
Thanks @fire-poy  for finding it, reporting
it and find the cause.

UserLambda hotfix

---

frontend/src/components/profile/Friend.tsx

add a link to `/user/${username}` on the name of the user
Code [example of custom link](https://github.com/remix-run/react-router/blob/dev/examples/custom-link/src/App.tsx)
I started with this
[use link props](https://reactnavigation.org/docs/use-link-props/#options)
but we use react router and not
reactnavigation
Click on the username on a friend in the friendlist

frontend: profile add link on the username

---

backend/src/app.module.ts
backend/src/auth/auth.controller.ts
backend/src/auth/guards/authenticated.guard.ts
backend/src/decorators/public.decorator.ts
backend/src/user/user.controller.ts

The 'authenticated.guard' guard is now used globally throughout the backend. If you want it not to be used on a certain endpoint you must use the @Public decorator.
Docs:
https://docs.nestjs.com/security/authentication#enable-authentication-globally

Global usage of authenticated.guard

---

frontend/src/pages/MainProfile.tsx

Here is a fix for this warning when reloading /profile.
What is going on?
the loader is fetching user before rendering but the user is updated on the component rendering like that:
```
const fetchUserData = useLoaderData() as UserData
const dispatch = useAppDispatch()
dispatch(userActions.update({ user: fetchUserData }))
```
because you cannot use react Hooks outside of react components.
The problem is that UserInformation is trying to fetch userData from the store at the (almost) same time that it is being updated.
Solution:
in the loader you can use :
```
store.dispatch(userActions.update({ user: data }))
```
to update user before rendering and store.dispatch() is not a react Hook.

warning when reloading profile fix

---

frontend/src/App.tsx

Every page share the same loader that gets the user in the back and update the Redux store before rendering.
This means that when we reload any page the store will be wiped out and the user will be automatically re-stored.
It is not what I wanted to do at first but it works and it is simple.
that's the #100 PR 
🚀 🚀 🚀 🚀

userLoader for every page

---

backend/src/room/room.controller.ts

Normally, the only endpoints that use the 
@Public decorator are the ones that we do 
not want to protect with the general 
guard. 
Since this is not the case for this group 
of endpoints, we must delete the 
decorator. 
I forgot to delete it at the end of the 
tests and before doing the last PR.

E delete @Public decorator from 'room' controller

---

backend/src/app.module.ts

It is, IMHO, a security improvement,
that avoids to set a env file by error
* https://docs.nestjs.com/techniques/configuration#disable-env-variables-loading

backend: ignore env file

---

.gitignore
Makefile
docker-compose.yml
scripts/create-env.sh

In my opinion, it is clearer
> done: c96b6a7c0a7d6a3a4117bb474681725e903002ac
> see (#70)
**WILL NOT BE DONE, OUTSIDE THE SCOPE**

ops: all environement variables in one file

---

backend/src/match/dto/create-match.dto.ts
backend/src/pong/pong.gateway.ts
backend/src/pong/pong.service.ts
backend/src/room/room.controller.ts
backend/src/room/room.service.ts
frontend/src/components/pong/BoardGame.tsx
frontend/src/main.tsx
frontend/src/pages/Play.tsx

This pull request introduces several key changes that aim to improve the gameplay experience and backend logic of our Pong game.
- Refactor Match Data Transfer Object (DTO): I have updated the CreateMatchDto to better reflect the game's scoring system. 
- Paddle Collision Logic: The collision logic for both the left and right paddles has been refined. Previously, the ball would rebound even if it had already passed the paddle's x-position but was still within the y-range of the paddle. The updated collision logic now correctly considers the position of the ball, ensuring it only bounces back when it has not yet exceeded the respective paddle in the x axis.
- Updated Score System: The PongService has seen changes in the scoring logic. I have removed the automatic game reset when a player …

Pong: save match in data base and improvement of coalition logic

---

backend/src/typeorm/channel-user-muted.entity.ts

When you delete a channel with a muted user, with option onDelete: 'CASCADE', in muted user entity now the channel can be deleted

muted cascade

---

backend/src/auth/auth.service.ts
backend/src/auth/guards/authenticated.guard.ts
backend/src/auth/guards/oauth.guard.ts
backend/src/auth/session.serializer.ts
backend/src/auth/strategies/auth42.strategy.ts

If the player tries to log in on one device when he is already logged in on another, he will not be able to access the resources and will receive an error.

E avoid double login

---

frontend/src/components/chat/userBox/UserBox.tsx
frontend/src/components/chat/userBox/UserComponent.tsx

If there is no banned user in channel banned title it's not showed.
If UserComponent is banned you can't set/unset admin, nor mute User.
The same if UserComponent is DM
If User is admin all implementation of the menu is equal than if user is owner

banned menu

---

frontend/src/components/error/Error.tsx

if a user is not logged in and tries to go to a existing page , he is redirect to the sign in page ("/") and doesn't see the 400 error page anymore.

redirect to "/"

---

frontend/src/components/profile/UserInformation.tsx

In production, nginx send a 413 http error when the user try to send a too large file.
Manage the 413 with a alert window

frontend: alert the user when the file is too large

---

scripts/create-env.sh

When we are creating the `.env` file, we need that docker is running to generate password.
So, first check if docker is running before to continue

script: check if docker is running
