Makefile, docker-compose.yml
not to confuse the docker volume(our-data)
and the database(our-data) in the
PostgreSQL and therefore rename our docker
volume with "our-volume"
```bash
sed -i 's/our-data/our-volume/g' \
Makefile docker-compose.yml
```
=> rename docker volume

Makefile
Two new commands in Makefile for lazy developers.
When you need to pass a command inside a container.
=> two new make commands : cmd-back, cmd-front

.prettierignore
=> prettierignore

frontend/index.html
=> title: rename title

frontend/src/index.css
* css remove line length
The title signin page isn't hide anymore
=> frontend: css

frontend/src/components/navigation/Navbar.tsx
Add the 42 website on the 42 logo
see "target" attribute on:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#attributes
=> frontend: add 42 link

frontend/src/App.tsx
One line has been deleted by error while rebasing the branch, making /tmp unavailable.
This fix the problem.
=> patch for /tmp that was deleted during rebase

backend/entrypoint.sh
we don't need to build files during the
development
=> backend: do not build

README.adoc
=> README: change title

frontend/src/components/navigation/Navbar.tsx
consistency, add a space to cosmicpong
=> frontend: add space to cosmicpong

backend/src/main.ts, backend/src/player/dto/create-player.dto.ts
By adding the option 'whitelist: true'
to 'ValidationPipe' we eliminate all
the unexpected data that may be sent
to us in HTTP requests.
* https://docs.nestjs.com/techniques/validation#stripping-properties
* similar error: [stackoverflow](https://stackoverflow.com/questions/69301154/null-value-in-column-of-relation-violates-not-null-constraint-nestjs)
=> Avoiding malicious data in the requests

frontend/src/components/tempLogin/TempForm.module.css, frontend/src/components/tempLogin/TempPlayerLi.module.css
We have our special white in `--color-white`
```bash
sed -i \
's/ white/ var(--color-white)/g' \
$(find frontend/src -name "*.css")
```
=> frontend: use white keyword

frontend/src/components/tempLogin/TempForm.module.css, frontend/src/components/tempLogin/TempPlayerLi.module.css
Just format source files
```bash
make format
```
=> format code

create-env.sh
=> create-env.sh: prompt for API credentials

README.adoc
See the [**preview**](https://github.com/eprei/ft_transcendence/tree/t_readme_contributors#contributors)
* https://docs.asciidoctor.org/asciidoc/latest/macros/images/
* https://docs.asciidoctor.org/asciidoc/latest/tables/build-a-basic-table/
=> README: add contributors list

README.adoc
All technologies we use for this project
see a [preview](https://github.com/eprei/ft_transcendence/tree/t_readme_technologies#technologies)
=> README: add list of technologies

frontend/src/components/navigation/Navbar.module.css
this branch just fix this bug:
I have just deleted one css ligne.
=> 42.svg upload bug fixed

frontend/src/components/pong/BoardGame.tsx
- frontend: change ctx type
- frontend: define the Rectangle type
> For more informations,
read each commit description
=> frontend: few fix pong component

frontend/src/components/profile/Friend.tsx
I think the curly brackets are useless
=> frontend: remove extra curly bracket

backend/src/user/dto/update-nickname.dto.ts, backend/src/user/user.controller.ts, backend/src/user/user.service.ts, frontend/src/components/profile/ClickableIcon.tsx, frontend/src/components/profile/UserInformation.tsx
Now the user can change his nickname by
pressing the pencil icon next to his name.
Then enter a text and press enter.
If the user provides a nickname that
already exists in the database he will
receive an error.
If he provides an empty string, he will
receive an error.
If he provides an available nickname, it
will be updated in the database and the
frontend page will be reloaded showing the
new name.
This functionality is not explicitly
protected against SQL injections as no
user data is sanitized. It only validates
your input taking into account that it is
not an empty string. As far as I
understand TypeORM does a great job
protecting us against SQL injections. If
more security is needed we can implement
it.
=> E edit nickname

backend/src/auth/auth.controller.ts, backend/src/user/user.controller.ts, backend/src/user/user.service.ts, frontend/src/App.tsx, frontend/src/ProtectedSignIn.tsx, frontend/src/components/TFAVerify/TwoFactorVerificationBox.tsx, frontend/src/components/navigation/LogOutButton.module.css, frontend/src/components/navigation/LogOutButton.tsx, frontend/src/components/navigation/Navbar.tsx, frontend/src/components/profile/Statistics.tsx, frontend/src/pages/TFAAuthenticate.tsx, frontend/src/pages/TFATurnOn.tsx, frontend/src/store/auth.tsx
Implementation of routing based on actual
login status.
Being on the SignIn page, if the user
accesses successfully with login 42 and
does not have 2fa enabled, he is
redirected to the profile page.
Being on the SignIn page, if the user
successfully logs in with login 42 and has
2fa enabled, he/she will be redirected to
the 2fa verification page. If he/she
enters a correct code, he/she is
redirected to the profile page.
If the user is already fully authenticated
but tries to log in to the SignIn page,
he/she is redirected to the profile page.
Added logout button (need to improve the
css because it is not readable when
hovering the mouse over the button).This
button is available in the Navbar and in
the 2fa verification page.
=> 2fa redirection

Makefile
We can verify if the code is compilable
1. build
```bash
make build
```
=> makefile: make build

backend/src/user/user.controller.ts, frontend/src/App.tsx, frontend/src/components/TFATurnOn/CodeQR.tsx, frontend/src/components/UserLambda/UserLambdaInformation.tsx, frontend/src/components/pong/BoardGame.tsx, frontend/src/components/profile/StatisticsLambda.tsx
When we run 'make build' several errors appear that do not allow the compilation to finish successfully.
Mainly caused by items that were imported and not used. 
Also fixed a compatibility issue between the UserLambda element and the use of ProtectedRoutes that caused the /user/nickname page to not work correctly.
=> Fix for compile-time issues

frontend/src/App.tsx, frontend/src/RootLayout.tsx, frontend/src/components/error/Error.tsx, frontend/src/pages/MainProfile.tsx
This feature is Loading the user.status (isLogged or need2fa or error) in RootLayout as a loader.
(before it was in a useEffect function in App component.)
It is better to have it in a loader as the frontend rendering is dependent of the user.status. And RootLayout is more appropriate than App, imo.
While testing the ErrorPage, I have found that the simple error page that is called when going to a page that doesn't exists isn't fonctionning well anymore. I fix that in the last commit.
=> R load user in store

frontend/package-lock.json, frontend/package.json, frontend/src/components/profile/UserInformation.tsx
Changed handleFileChange() that was using axios library, to use a simple fetch.
Uninstalled axios library from package.json
=> changed function with axios to fetch and uninstall axios

frontend/src/components/navigation/Navbar.module.css, frontend/src/components/navigation/Navbar.tsx
logout button in navbar not moving links anymore
=> logout button in navbar not moving links anymore

frontend/src/components/profile/CustomLink.tsx, frontend/src/components/profile/Friend.tsx, frontend/src/components/profile/OtherUsers.tsx
Move CustomLink out of Friend.tsx and OtherUsers.tsx.
And import it in each of them.
=> R front fetch myfriends custom link

frontend/src/components/profile/StatisticsLambda.tsx
=> Victorires -> Victories

backend/package-lock.json, backend/package.json, backend/src/app.module.ts, backend/src/pong/dto/create-pong.dto.ts, backend/src/pong/dto/update-pong.dto.ts, backend/src/pong/entities/pong.entity.ts, backend/src/pong/pong.gateway.ts, backend/src/pong/pong.module.ts, backend/src/pong/pong.service.ts, frontend/package-lock.json, frontend/package.json, frontend/src/components/pong/BoardGame.tsx
The frontend emit (send a request) to backend,
the backend reply by a `Frame` object.
The frontend render the object by the same way
* npm install: socket.io-client
```bash
docker exec our-frontend npm install \
socket.io-client
```
* npm install: @nestjs/platform-socket.io
```bash
docker exec our-backend npm install \
@nestjs/platform-socket.io
```
* npm install: @nestjs/websockets
```bash
docker exec our-backend npm install \
@nestjs/websockets
```
* nestcli: generate resource pong
```
nest g res pong --no-spec
? What transport layer do you use? WebSockets
? Would you like to generate CRUD entry points? Yes
```
=> game: websocket

frontend/src/RootLayout.tsx
this part is now done in the loader, before rendering for better performance.
```
if (data.status === 'isLogged') {
dispatch(authActions.login())
} else if (data.status === 'need2fa') {
dispatch(authActions.setNeed2fa())
} else {
dispatch(authActions.logout())
}
```
=> RootLayout loader is doing the dispatch

backend/src/auth/auth.controller.ts, backend/src/auth/auth.service.ts, backend/src/auth/strategies/auth42.strategy.ts, backend/src/main.ts, backend/src/user/user.service.ts
Just cleaning up some console.log that in my opinion, shouldn't be on stage.
When you start a new branch, you have to dig thru all the logs to find yours.
If there is something that you really want to keep, let me know in comments and I will put it back
=> R stage cleanup

backend/src/friend/friend.controller.ts, backend/src/user/user.service.ts
I was looking for this error when you click on any friend name on Profile:
I found it in findByNickname() in user.service.
It was a very strange function Promisified by hand, so I rewrite it.
I also clean up friend controllers functions that had some useless variables.
=> R friend backend improvement

backend/src/app.service.ts, backend/src/auth/auth.controller.ts, backend/src/auth/strategies/auth42.strategy.ts, backend/src/main.ts, backend/src/user/user.service.ts, docker-compose.yml
- docker-compose: add URLs environment
- frontend url
- backend url
- backend: apply `URL_BACKEND`
- backend: apply `URL_FRONTEND`
* https://docs.nestjs.com/techniques/configuration
=> backend: use a environment variable for URLs

backend/src/chat/chat.gateway.ts, frontend/src/components/chat/channelBox/discoverChannels/DiscoverItem.tsx, frontend/src/components/chat/channelBox/dmChannels/DmItem.tsx, frontend/src/components/ui/modal/NewChannelForm.tsx, frontend/src/pages/Chat.tsx
Small improvment for chat socket.
add 'chat' namespace.
implements OnGatewayInit, OnGatewayConnection, OnGatewayDisconnect on chat socket.
Add some logs when client connect and disconnect.
Format.
=> R chat socket imp

frontend/src/pages/Chat.tsx, frontend/src/sockets/SocketChat.ts
The socket for chat is imported from src/sockets/SocketChat.ts
All socket.on() listeners are declared inside useEffect and cleaned up in the return.
Thanks to @epresa-c for showing me the way.
=> socketChat

frontend/src/components/history/MatchList.module.css, frontend/src/components/history/MatchList.tsx, frontend/src/components/profile/Friend.module.css, frontend/src/components/profile/FriendList.module.css, frontend/src/components/profile/UserInformation.module.css, frontend/src/pages/Chat.module.css, frontend/src/pages/MainProfile.module.css, frontend/src/pages/MatchHistory.tsx, frontend/src/pages/Play.module.css, frontend/src/pages/TFA.module.css, frontend/src/pages/UserLambda.module.css, frontend/src/pages/UserLambda.tsx
Every Page are responsive for smaller screen.
The breaking point for most page is 770px.
=> Css responsive

frontend/src/components/pong/BoardGame.tsx, frontend/src/sockets/SocketGame.ts
Use a global socket for game in the same way that a global socket is used for chat in r_chat_socket
=> E socket global game

backend/src/typeorm/channel-user-muted.entity.ts, frontend/src/pages/Play.tsx
=> Add Original theme to pong

backend/src/match/match.service.ts, backend/src/typeorm/channel-user-muted.entity.ts, frontend/src/components/history/MatchList.tsx, frontend/src/pages/UserLambda.tsx, frontend/src/types/MatchData.ts
the channel muted history file change is due to a make format call
So I added level in the component, shows up on MatchHistory and UserLambda
=> add level to matchlist

frontend/src/components/chat/chatBox/Msg.module.css, frontend/src/components/chat/userBox/User.module.css, frontend/src/components/chat/userBox/User.tsx
If user == owner    color = purple
If user == admin    color = mid-green
If user == user       color = white
Picture dosen't distord anymore
=> user color by range

backend/src/chat/chat.gateway.ts, backend/src/chat/chat.service.ts, frontend/src/assets/icon/lock.svg, frontend/src/components/chat/channelBox/ChannelLi.module.css, frontend/src/components/chat/userBox/User.tsx, frontend/src/pages/Chat.tsx
If user is blocked frontend dosen't show icon to send DM
In Backend is also a check for avoiding unwanted messages.
Also Lock of private channels is changed to be a little less degueulasse
=> blocked dm

backend/src/user/user.controller.ts, backend/src/user/user.module.ts, backend/src/user/user.service.ts, frontend/src/App.tsx, frontend/src/components/UserLambda/UserLambdaInformation.module.css, frontend/src/components/UserLambda/UserLambdaInformation.tsx
Now we can block user from public profile page (UserLambda)
=> public profile block

backend/src/chat/chat.gateway.ts, frontend/src/pages/Chat.tsx
fix the bug that was showing only the last msg send.
It's the second time I PR this fix because I close it by error. Sorry
=> Chat fixed

backend/src/pong/pong.gateway.ts, backend/src/room/dto/create-room.dto.ts, backend/src/room/room.service.ts, frontend/src/components/chat/chatBox/Msg.module.css, frontend/src/components/chat/userBox/User.module.css, frontend/src/components/chat/userBox/User.tsx, frontend/src/components/history/MatchList.tsx, frontend/src/components/pong/BoardGame.module.css, frontend/src/components/pong/BoardGame.tsx, frontend/src/pages/Chat.tsx, frontend/src/pages/MainProfile.module.css, frontend/src/pages/MainProfile.tsx, frontend/src/pages/MatchHistory.tsx, frontend/src/pages/Play.tsx, frontend/src/pages/UserLambda.tsx, frontend/src/sockets/InvitationHandler.module.css, frontend/src/sockets/InvitationHandler.tsx
Invite another user to play
The management of receiving invitations for the moment is only added on the profile page. When this PR is validated, I will make an extra commit to add the same methods in all other pages except game. 
Temporarily and to test the functionality, I enabled the possibility to invite yourself to play.
This will be removed once the PR is validated.
How to test it:
- Login to cosmic pong in an incognito window (to the profile page as it is the only one that manages invitations so far)
- Login to cosmic pong in a normal window and go to chat. Enter a channel and click on the joystick icon next to our own user in order to invite us to play ourselves.
You should receive an invitation in the incognito window.
Test the different possibilities...
=> E invite to play

backend/src/friend/friend.controller.ts, backend/src/friend/friend.service.ts
Clean useless functions.
Add try catch in controller and throw appropriate Error if catch()
=> friend resource

backend/src/room/room.controller.ts, backend/src/room/room.service.ts
Clean up useless functions
Add exception to deletRoom() and UsePipe to createRoom()
=> cleaning room resource

backend/src/pong/pong.gateway.ts, backend/src/user/user.controller.ts
=> backend: use environment variables

backend/src/match/match.controller.ts, backend/src/match/match.service.ts
Clean up useless functions
Add ValidationPipe and throw errors
=> clean match resource

frontend/src/components/pong/BoardGame.tsx
Correction of a problem that prevented
the correct fetch of user information
on the screen of player number two
=> Bugfix fetch user info in game

frontend/src/components/chat/channelBox/dmChannels/DmItem.tsx, frontend/src/components/chat/channelBox/joinedChannels/JoinedItem.tsx, frontend/src/components/profile/UserInformation.tsx, frontend/src/pages/Chat.tsx, frontend/src/store/chat.tsx
fix infinite loop in /profile
block/unblock user fix
=> R chat block

backend/src/chat/chat.gateway.ts, frontend/src/pages/Chat.tsx
channel appear for everyone and not for the creator only
=> channel appear for everyone

backend/src/chat/chat.service.ts, frontend/src/components/chat/userBox/UserComponent.tsx
muted work always, await was missing in backend
=> muted working always

backend/src/auth/auth.service.ts
When the user is created in the DB with the nickname of 42, it checks that it is not already in use and if it is, it create a random 5 char string as a nickname.
=> random string if nickname already used

backend/src/user/user.service.ts, frontend/src/components/profile/UserInformation.tsx
The user receive an alert() if he tries to change his nickname to a one that does already exists in the DB.
(You can try it by changing your nickname by the same nickname)
I know alert() is not very nice but some feedback is better than nothing
=> R alert if exists

backend/src/chat/chat.gateway.ts, backend/src/chat/chat.service.ts, frontend/src/components/chat/channelBox/CreateNewCh.tsx
There is an alert if a user tries to create a channel with a name that is already in use.
Same idea than with user nickname.
=> alert if try to create a channel with same name

scripts/create-env.sh
Type Y, y or just enter with nothing, to put the machine hostname in the HOSTNAME variable
If you type n for no, you get `localhost` in the HOSTNAME variable
Oh and chatgpt corrected some typos, sorry for bothering :) but it works I tested it
=> Add condition to choose between hostname and localhost in make env script

backend/src/friend/friend.controller.ts, backend/src/friend/friend.module.ts, backend/src/pong/pong.gateway.ts, backend/src/pong/pong.module.ts, backend/src/user/user.module.ts, backend/src/user/user.service.ts, frontend/src/pages/MainProfile.tsx
Profile is using socket to get updated about other user status and is not sending requestes every 3 sec anymore.
=> profile is using socket

backend/src/chat/chat.gateway.ts
@t-h2o  This is a really safe PR, trust me. I'm a brogramer 😎
=> add security to socket chat

backend/src/chat/chat.gateway.ts, backend/src/pong/pong.gateway.ts, backend/src/user/user.service.ts, frontend/src/components/UserLambda/UserLambdaInformation.tsx, frontend/src/components/navigation/LogOutButton.tsx, frontend/src/components/pong/BoardGame.tsx
- When the user closes the window its state changes to ofline.
- During the game, the case is handled when the user closes the window so that the game is terminated and the other player is notified.
- Addition of a formerly accepted PR.
- Make format.
=> E socket disconnect when close window

docker-compose.yml, frontend/src/RootLayout.tsx, frontend/src/components/TFATurnOn/CodeQR.tsx, frontend/src/components/TFAVerify/TwoFactorVerificationBox.tsx, frontend/src/components/UserLambda/UserLambdaInformation.tsx, frontend/src/components/chat/userBox/UserComponent.tsx, frontend/src/components/history/MatchList.tsx, frontend/src/components/navigation/LogOutButton.tsx, frontend/src/components/play/MatchSystemBtn.tsx, frontend/src/components/pong/BoardGame.tsx, frontend/src/components/profile/Friend.tsx, frontend/src/components/profile/OtherUsers.tsx, frontend/src/components/profile/UserInformation.tsx, frontend/src/components/signin/MainSection.tsx, frontend/src/components/signin/SignInBtn.tsx, frontend/src/pages/MainProfile.tsx, frontend/src/pages/Play.tsx, frontend/src/pages/TFAAuthenticate.tsx, frontend/src/pages/TFATurnOn.tsx, frontend/src/pages/UserLambda.tsx, frontend/src/sockets/SocketChat.ts, frontend/src/sockets/SocketGame.ts, frontend/vite.config.ts
- vite: environment variables
> see see documentation [viteJS](https://vitejs.dev/config/#using-environment-variables-in-config)
- add `VITE_URL_FRONTEND`
- add `VITE_URL_BACKEND`
- url frontend
```bash
sed -i \
"s~\`http://localhost:4040~\`\${import.meta.env.VITE_URL_FRONTEND}~g" \
$(find frontend/src -type f -name "*.ts*")
sed -i \
"s~'http://localhost:4040/\(\(\w\+/\?\)*\)'~\`\${import.meta.env.VITE_URL_FRONTEND}/\1\`~g" \
$(find frontend/src -type f -name "*.ts*")
```
- url backend
```bash
sed -i \
"s~\`http://localhost:8080~\`\${import.meta.env.VITE_URL_BACKEND}~g" \
$(find frontend/src -type f -name "*.ts*")
sed -i \
"s~'http://localhost:8080/\(\(\w\+/\?\)*\)'~\`\${import.meta.env.VITE_URL_BACKEND}/\1\`~g" \
$(find frontend/src -type f -name "*.ts*")
```
=> frontend: environment URL

scripts/cmd-back.sh
- check docker command
- replace `==` by `=`
=> script: improve cmd back

backend/src/pong/pong.gateway.ts, frontend/src/components/pong/BoardGame.tsx, frontend/src/pages/Chat.tsx
The game now reacts when a user closes the window or his internet connection is involuntarily interrupted.
make format
=> E hotfix game refresh

Makefile
One command to restart when credentials change
=> T build makefile upgrade

frontend/src/components/TFAVerify/TwoFactorVerificationBox.tsx
=> frontend: auto tab digit
